### ISSUE TITLE
ide-helper:macro

### ISSUE THREAD

**Issue by woodynew** [friendsofhyperf/ide-helper#2]
/opt/www # php ./bin/hyperf.php ide-helper:macro
Generating optimized autoload files
Generated optimized autoload files containing 5228 classes

PHP Fatal error:  During inheritance of Iterator: Uncaught ErrorException: Return type of JsonSchema\Iterator\ObjectIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:42
Stack trace:
#0 /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php(17): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 /opt/www/vendor/composer/ClassLoader.php(582): include('...')
#2 /opt/www/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /opt/www/vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php(68): ReflectionClass->__construct()
/opt/www # php ./bin/hyperf.php ide-helper:macro
Generating optimized autoload files
Generated optimized autoload files containing 5228 classes

PHP Fatal error:  During inheritance of Iterator: Uncaught ErrorException: Return type of JsonSchema\Iterator\ObjectIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:42
Stack trace:
#0 /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php(17): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 /opt/www/vendor/composer/ClassLoader.php(582): include('...')
#2 /opt/www/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /opt/www/vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php(68): ReflectionClass->__construct()
#5 /opt/www/vendor/hyperf/collection/src/Arr.php(328): FriendsOfHyperf\IdeHelper\Command\MacroCommand->FriendsOfHyperf\IdeHelper\Command\{closure}()
#6 /opt/www/vendor/hyperf/collection/src/Collection.php(944): Hyperf\Collection\Arr::mapWithKeys()
#7 /opt/www/vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php(80): Hyperf\Collection\Collection->mapWithKeys()
#8 /opt/www/vendor/hyperf/command/src/Command.php(428): FriendsOfHyperf\IdeHelper\Command\MacroCommand->handle()
#9 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#10 {main} in /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php on line 17

Fatal error: During inheritance of Iterator: Uncaught ErrorException: Return type of JsonSchema\Iterator\ObjectIterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:42
Stack trace:
#0 /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php(17): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 /opt/www/vendor/composer/ClassLoader.php(582): include('...')
#2 /opt/www/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /opt/www/vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php(68): ReflectionClass->__construct()
#5 /opt/www/vendor/hyperf/collection/src/Arr.php(328): FriendsOfHyperf\IdeHelper\Command\MacroCommand->FriendsOfHyperf\IdeHelper\Command\{closure}()
#6 /opt/www/vendor/hyperf/collection/src/Collection.php(944): Hyperf\Collection\Arr::mapWithKeys()
#7 /opt/www/vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php(80): Hyperf\Collection\Collection->mapWithKeys()
#8 /opt/www/vendor/hyperf/command/src/Command.php(428): FriendsOfHyperf\IdeHelper\Command\MacroCommand->handle()
#9 [internal function]: Hyperf\Command\Command->Hyperf\Command\{closure}()
#10 {main} in /opt/www/vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php on line 17
/opt/www #

**Comment by huangdijia** [comment]
```shell
 php -v; composer info|grep friendsofhyperf
```
看看输出

**Comment by woodynew** [comment]
> ```shell
>  php -v; composer info|grep friendsofhyperf
> ```
> 
> 看看输出

/opt/www #  php -v; composer info|grep friendsofhyperf
PHP 8.1.17 (cli) (built: Mar 20 2023 23:27:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
friendsofhyperf/ide-helper         v3.0.47 The ide-helper component for Hyperf.

**Comment by xuanyanwow** [comment]
组件的实现原理是：通过composer的autoload_classmap文件扫描所有组件源码，判断每一个类是否包含 Trait `Macroable::class`

如果有包含该Trait，则进行下一步的处理，如果没有则跳过

```php
// vendor/friendsofhyperf/ide-helper/src/Command/MacroCommand.php:65
        ->mapWithKeys(function ($path, $class) {
              try {
                  $reflection = new ReflectionClass($class);
                  $traits = array_keys($reflection->getTraits() ?? []);

                  if (empty($traits) || ! in_array(Macroable::class, $traits)) {
                      return [];
                  }

                  return [$class => $reflection];
              } catch (Throwable $e) {
                  $this->warn($e->getMessage(), 'v');
                  return [];
              }
          })
```


在扫描和反射其他组件的代码时候，因为其他组件`未兼容新版PHP`的错误（需要声明返回值类型等新特性），产生的报错，输出日志  ` $this->warn($e->getMessage(), 'v');`  不影响使用


在你提供的报错中，是这个包导致的错误`vendor/justinrainbow/json-schema/src/JsonSchema/Iterator/ObjectIterator.php:42`
